### ISSUE TITLE
w3c is iffy on complex vs compound in nth-child and possibly other lists

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/soupsieve#135]
I'm not sure if this will affect us, but I figure I'll create an issue to track this. It seems that there was some concern with whether `:nth-child(an+b of)` should support compound or complex selectors. The idea is that it may be easier to get compound out the door first for L4, and then complex would be deferred to L5. The discussion seems to question others as well such as `:is()`, `:not()`, etc.

If they defer to L5, I don't think anything for us will change. If that is the case, we'll just say we support L5. If they completely abandon complex in one or more, we may have to downgrade complex support to compound.

**Comment by facelessuser** [comment]
From W3C's recent update on the relevant issue: 

>  RESOLVED: Defer complex selectors for all of these selectors and have a note in the current level mentioning this is an enhancement we'll get to in the next level

It appears the plan is to not implement complex selectors in relevant selectors in L4. This work will be deferred to L5. Webkit appears to have already done this work, and it sounds like that is okay, and it will just be noted that they support L5 in this regard.

It sounds like the idea behind this is to make the implementation easier so browsers will hurry up and implement the relevant selectors sooner rather than later. This is meant to make it easier on them.

As far as we are concerned, it sounds like we also will be supporting L5 variants. I imagine there is no additional work that needs to occur for us, and we can leave things as is.

**Comment by facelessuser** [comment]
At most, maybe we'll update tests and documentation to mention some L5 support, and maybe remove general statements that we are a CSS 4 implementation (as CSS 4 never will be), but we are simply an implementation that contains support for Level 3, Level 4, Level 5, etc., or modern CSS.

**Comment by squidfunk** [comment]
I came across your repository while searching for selector engine implementations (as I'm currently writing one myself) and boy, you must have had fun with pseudo classes. At least I have.

As an FYI: Safari (10, macOS) already supports complex selectors in the `of` clause, so it's funny and a little concerning they dropped it from level 4. Also no mention of it in the current [ED](https://drafts.csswg.org/selectors/#the-nth-child-pseudo). This actually works:

```
:nth-child(2n of html body *) {
  color: red;
}
```

**Comment by facelessuser** [comment]
> as I'm currently writing one myself

You are a brave man sir. Welcome to the weird and obsessive world of interpreting vague information is specifications :slightly_smiling_face:. 

> and boy, you must have had fun with pseudo classes

Yeah...*fun* :upside_down_face: .

> As an FYI: Safari (10, macOS) already supports complex selectors in the of clause, so it's funny and a little concerning they dropped it from level 4. Also no mention of it in the current ED.

Yeah, Safari is kind of an outlier. I feel there is a couple of things they currently support that other browsers do not. I'm happy to see they interpreted it the same as I did!

I am also a little concerned about the drop in level 4. From what I can gather from the the conversations I've read, there are browsers dragging their feet on features like this. I think full complex support was descoped to try encourage quicker adoption. I wish other browsers were as ambitions sometimes as Safari is....I also wish I liked Safari more than I actually do as well :slightly_smiling_face: .

From what I've seen, things move like molasses in the CSS spec. There are often half baked ideas as well, which is why some of the ideas get dropped. I think moving forward, I may be a bit more cautions on how quickly I adopt changes.

Luckily for me, due to the environment Soup Sieve operates in, I get to ignore things like Pseudo Elements and content that is influenced by user interactions etc. Takes a little of the complexity out of it, but still leaves quite a lot as well.

I share your interest and pain in this path you've chosen to walk. Feel free to share any other insights. There are things, at times, that I'm only 80% confident that I've done correctly.

**Comment by squidfunk** [comment]
> Yeah, Safari is kind of an outlier. I feel there is a couple of things they currently support that other browsers do not. I'm happy to see they interpreted it the same as I did!

I was quite amazed to see that Safari seems to support the biggest subset of level 4. I'm also not a fan of it and there are a few rendering bugs that are not fixable... at all. Had a lot of fun with the Material theme.

Definitely a world of pain.

What I love about your pseudo class implementation is the self-referential flavor (as I read and understood it, but I'm not good in Python), meaning you implemented pseudo selectors with selector lists themselves. At least what I've seen in the parser. Pretty cool. Together with the test cases this helped me a lot getting my implementation "right" (haha).

The use case of my implementation might be a little different than yours, as I'm also interested in selectors that _might_ match, like for example `:hover` and `:focus`. I implemented this using ternary logic yielding values of `true`, `false` and `undefined`. This feels quite natural and works very well. For example I know that `:valid` _might_ match `input` but will definitely not match `p`. Moving from simple selectors up to compound selectors, `undefined && true = undefined`, `undefined && false = false`, as `undefined` might both be `true` and `false`. And so on.

Let's call it Schroedinger's Selector Engine.

**Comment by squidfunk** [comment]
Oh and ... `fieldset`. I mean what the...  I think that's all I have to say 😂

**Comment by facelessuser** [comment]
> What I love about your pseudo class implementation is the self-referential flavor (as I read and understood it, but I'm not good in Python), meaning you implemented pseudo selectors with selector lists themselves. At least what I've seen in the parser. Pretty cool. Together with the test cases this helped me a lot getting my implementation "right" (haha).

Yeah, I created some shortcuts for myself.  I figured the building blocks where there as some pseudo-classes can be represented with work already done. There are some exceptions, and in those cases I force those particular cases to go through specific logic.

> The use case of my implementation might be a little different than yours, as I'm also interested in selectors that might match, like for example :hover and :focus. I implemented this using ternary logic yielding values of true, false and undefined. This feels quite natural and works very well. For example I know that :valid might match input but will definitely not match p. Moving from simple selectors up to compound selectors, undefined && true = undefined, undefined && false = false, as undefined might both be true and false. And so on.

That's very interesting. I imagine your environment is probably different than mine. As my target audience is scraping with Beautiful Soup, I have to return something or nothing, so it was very much hard booleans.

I'd love to get around to implementing `:valid` and `:invalid` as it sounds like you did, but I still have to bridge the gap in Python regular expressions and JavaScript. I imagine your implementation is in JavaScript.  That would've made it much easier for me to implement....one of these days :slightly_smiling_face:.

> Oh and ... fieldset. I mean what the... I think that's all I have to say joy

:100: 

I think the whole journey was kind of interesting. Trying to figure out the times I was clearly overthinking things, and times I wasn't thinking about things enough. I'm kind of happy I'm at a state where I can just focus on refining hiccups in logic. Though...once I finally understand the intentions behind `:nth-col` support, I plan on diving into that. It's just too vague for me right now. Every time I sit down to think about it, I just think of all the corner cases I'm unsure about :man_shrugging: .

**Comment by squidfunk** [comment]
> That's very interesting. I imagine your environment is probably different than mine. As my target audience is scraping with Beautiful Soup, I have to return something or nothing, so it was very much hard booleans.

I think the ternary logic is only useful for analytical purposes, not for actual matching. Also using pseudo selectors for matching when writing a crawler might not be the most stable approach, apart from maybe the tree structural selectors (`nth-child` and friends).

> I'd love to get around to implementing :valid and :invalid as it sounds like you did, but I still have to bridge the gap in Python regular expressions and JavaScript. I imagine your implementation is in JavaScript. That would've made it much easier for me to implement....one of these days 🙂.

My implementation is written in TypeScript, yes, but it doesn't help a lot, as I'm (like you) matching CSS against HTML, two non-Javascript-native languages 🙂Okay, the types help a lot, actually, but that's not a feature that is exclusive to TypeScript. Another learning of my journey was the fact that implementing a CSS parser (even a selector parser) with regular expressions will not catch all cases that are valid in respect to Syntax Level 3. Sure, those might also rather be considered to be edge cases, which sadly I have to account for, like for example `./**/foo`, which is perfectly valid in all major browsers.

> I think the whole journey was kind of interesting.

It's amazing what one could learn about CSS! A lot of stuff I did not know, and I'm writing CSS for over a decade now.

> once I finally understand the intentions behind :nth-col support, I plan on diving into that. It's just too vague for me right now. Every time I sit down to think about it, I just think of all the corner cases I'm unsure about 🤷‍♂ .

No browser supports it, I think it's not worth exploring. At least that's what I decided.

**Comment by facelessuser** [comment]
> No browser supports it, I think it's not worth exploring. At least that's what I decided.

Agreed.

> `./**/foo`

Ugh, I think I generally do pretty good at allowing comments, but yeah, I don't support that. I think I only allow them in cases where whitespace is acceptable, which is like 99% of the cases, but apparently not all of them :slightly_smiling_face: .

Yeah, if you have to parse **all** valid CSS, which it sounds like you do, you have to look for that kind of stuff and have a finer resolution of how you tokenize. In my case, I'm close enough to be usable for the cases of my users.

**Comment by facelessuser** [comment]
This conversation reminded me that the documentation for this has already been updated mentioning our current direction. We mention the differences between level 3 and level 4 and mention that we follow the discussed level 5 direction. This issue can actually be closed as all of this is now addressed.

I think even if the CSSWG were to completely drop complex selectors, we might keep them around in Soup Sieve simply for their usefulness.  While we strive to follow the spec, we are not completely bound to it as we allow for things like `:contains()` etc.
