### ISSUE TITLE
Out of date 4.7 reference in API docs

### ISSUE THREAD

**Issue by tbm** [facelessuser/soupsieve#146]
https://facelessuser.github.io/soupsieve/api/ says:

> As far as the API is concerned, Soup Sieve mimics Beautiful Soup's original API at the time of writing this, which is why the names select and select_one are used. As of today, Beautiful Soup has agreed to include Soup Sieve as the official select library which is slated for the 4.7.0 release.

I think that's out of date now and can be removed (or slightly updated).

**Comment by facelessuser** [comment]
Thanks for the heads up! There were a couple of things that shouldn't have been in the docs anymore.  They've been removed.

**Comment by tbm** [comment]
Thanks for your fast reply!
