### ISSUE TITLE
The "id" attribute is not handled according to HTML5 specification

### ISSUE THREAD

**Issue by vertebarbe** [facelessuser/soupsieve#151]
The '#' in a selector seems to follow the HTML4 specifications, so a selector like this : `#1` raises a SelectorSyntaxError.

**Comment by facelessuser** [comment]
What specification are you referencing? In the current selector specification it states:

- https://www.w3.org/TR/selectors-4/#id-selectors (emphasis added):

> An ID selector consists of a “number sign” (U+0023, #) immediately followed by the ID value, which must be a CSS **identifier**. An ID selector represents an element instance that has an identifier that matches the identifier in the ID selector. (It is possible in non-conforming documents for multiple elements to match a single ID selector.)

Identifier rules:

- https://www.w3.org/TR/css-syntax-3/#identifier
- https://www.w3.org/TR/css-syntax-3/#ident-token-diagram

Browser implementation: 

```js
> document.querySelectorAll('#1')
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#1' is not a valid selector.
    at <anonymous>:1:10
```

You may want to use escapes:

- https://facelessuser.github.io/soupsieve/selectors/#escapes

Or if you are handling dynamic content, you can use the escape function:

- https://facelessuser.github.io/soupsieve/api/#soupsieveescape

Or am I missing something?

**Comment by vertebarbe** [comment]
Oh, I was referring to the specifications for the value of an id:

- https://www.w3.org/TR/html50/dom.html#the-id-attribute

> The value must be unique amongst all the IDs in the element's home subtree and must contain at least one character. The value must not contain any space characters.
There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

So since there could be ids equal to "1" or even "1abcd", I thought that the selectors should support these types of value. In my case I have to use `[id="1abcd"]` instead of `#1abcd`

**Comment by facelessuser** [comment]
I don't think `#1abcd` works in any browser.

You can do something like `'#{}`.format(soupsieve.escape('1abcd')`.  You can also just use `#\31 abcd`.

https://codepen.io/facelessuser/pen/PMbYgx?&editable=true

**Comment by vertebarbe** [comment]
So it is the selector specification itself that does not support hml5 ?

**Comment by vertebarbe** [comment]
Thank you for your quick response and your help, as I said I had already a workaround for websites that used these types of id, but I can see that this is not a problem in the implementation !

**Comment by facelessuser** [comment]
CSS syntax doesn't support ids that start with numbers unless you use an escape. HTML spec does support numbers, and you could even use weird unicode characters. People often will use CSS friendly ids to avoid this kind of issue as well, but it isn't invalid HTML. Same goes for classes.
