### ISSUE TITLE
wheel marked as p2-p3 while p2 is not supported

### ISSUE THREAD

**Issue by gokuatkai** [facelessuser/soupsieve#182]
pip install soupsieve from python2 will install version 2.0.0 while it doesnt support python2 anymore.
the wheel should not be built universally if it doesnt support p2.

**Comment by facelessuser** [comment]
How are you installing this?  We have this in our setup: `python_requires=">=3.5",`. Pip should honor this, right?

**Comment by facelessuser** [comment]
```
py -2.7 -m pip install -U soupsieve
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting soupsieve
  Using cached soupsieve-1.9.5-py2.py3-none-any.whl (33 kB)
Requirement already satisfied, skipping upgrade: backports.functools-lru-cache; python_version < "3" in c:\python27\lib\site-packages (from soupsieve) (1.5)
Installing collected packages: soupsieve
  Attempting uninstall: soupsieve
    Found existing installation: soupsieve 1.6
    Uninstalling soupsieve-1.6:
      Successfully uninstalled soupsieve-1.6
Successfully installed soupsieve-1.9.5
```

Looks fine to me 🤷‍♂. I'll need more information.

@gir-bot add T: bug, S: needs-confirmation
@gir-bot remove S: triage

**Comment by gokuatkai** [comment]
yes this is indeed strange, we are mirroring wheels in our internal cheeseshop server, using pypiserver, having wheel for pypi for soupsieve 1.9.5 and 2.0

```[root@ac226a410a64 app]# export PIP_INDEX_URL=https://REDACTED.com/wheels/centos/7/simple
[root@ac226a410a64 app]# pip install -U soupsieve
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://REDACTED.com/wheels/centos/7/simple
Collecting soupsieve
  Downloading https://REDACTED.com/wheels/centos/7/packages/soupsieve-2.0-py2.py3-none-any.whl (32 kB)
ERROR: Package 'soupsieve' requires a different Python: 2.7.5 not in '>=3.5'```

**Comment by gokuatkai** [comment]
From pypi `python_requires=">=3.5"` is respected, not from our pypiserver instance, I believe it comes from our server then, sorry for the inconvenience

**Comment by facelessuser** [comment]
No worries. If later there is something *reasonable* I can do, I'm happy to consider, but currently I think I'm doing everything I **should** be doing.

**Comment by facelessuser** [comment]
I think I know how to fix this. I need to remove the Universal from by setup.cfg: 

```
[wheel]
universal = 1
```

**Comment by gokuatkai** [comment]
We have found that the issue we have is because https://pypi.org/project/pypiserver/ does not have the feature of having `data-requires-python` in link from https://www.python.org/dev/peps/pep-0503/
if this can help someone.

**Comment by facelessuser** [comment]
Well, it looks like there are things for both of us to fix. With your server fix though, my setup.cfg issue is made moot. With that said, it will be more appropriate for me to remove the `univeral=1` flag as well in the next release.

**Comment by gokuatkai** [comment]
awesome thanks for considering it 👍
