### ISSUE TITLE
Wrong function used in API documentation example for soupsieve.select_one()

### ISSUE THREAD

**Issue by p0lm** [facelessuser/soupsieve#183]
The API documentation for `soupsieve.select_one()` (https://facelessuser.github.io/soupsieve/api/#soupsieveselect_one) uses the wrong function in the example code: 

```python3
def select(select, tag, namespaces=None, flags=0, **kwargs):
    """Select the specified tags."""
```
should be:

```python3
def select_one(select, tag, namespaces=None, flags=0, **kwargs):
    """Select the specified tags."""
```

**Comment by facelessuser** [comment]
Thanks! I'll try to get a fix in soon.

@gir-bot add T: bug, S: confirmed, C: docs
@gir-bot remove S: triage
