### ISSUE TITLE
Consider removing reference to `__file__`

### ISSUE THREAD

**Issue by n8henrie** [facelessuser/soupsieve#184]
Context: https://github.com/indygreg/PyOxidizer/issues/69

It looks like `__file__` is referenced [in util.py][0] in defining `MODULE`, but I don't see `MODULE` used anywhere in the project.

```console
$ git --no-pager grep MODULE
soupsieve/util.py:MODULE = os.path.dirname(__file__)
```

Using `__file__` prevents tools like pyoxidizer from being able to build a standalone binary; in turn, `beautifulsoup4` depends on this project, which means users can't use pyoxidizer to build standalone binaries of Python projects using bs4. (It looks like this line is the only reference to `__file__` anywhere in any of bs4's dependencies.)

Especially if `MODULE` isn't being used, would you consider removing this line? Many thanks for considering.

[0]: https://github.com/facelessuser/soupsieve/blob/883258418177123d04676c6ee1ce9b4a4054b957/soupsieve/util.py#L6

**Comment by facelessuser** [comment]
Is that even getting used?

**Comment by facelessuser** [comment]
Pulls are welcome, but I believe it can be pulled out.

**Comment by n8henrie** [comment]
`MODULE`? As far as I can tell no, as shown in my `git grep` above it looks like it is defined there and not referenced anywhere else in the codebase.

**Comment by facelessuser** [comment]
I must have been playing around with something weird and left it in on accident.

@gir-bot add T: maintenance
@gir-bot remove S: triage
