### ISSUE TITLE
Lower/upper performance

### ISSUE THREAD

**Issue by akx** [facelessuser/soupsieve#190]
Hey there,

I'm working on a project that's pretty heavy on using BS4 `.select`, and profiling it I noticed `soupsieve.utils.lower()` was the heaviest function (1.7 million calls, 5.6s time, 3.8s owntime). A couple of things:

* Why is a custom `lower()` implementation required, c.f. just `str.lower()`? I assume it has to do with `str.lower()` being unicode aware, and `lower()` is strictly ASCII only, but would be nice to have confirmation.
* Slapping a `lru_cache()` on `lower()` makes it all but disappear from the cProfile output (108 calls, zero time). I'm not sure if `lower` should be LRU cache annotated in the library itself, though?

**Comment by facelessuser** [comment]
CSS spec applies lower to ASCII. I don't think we use upper, I sort of just included it in case we needed it, we never did.

I need to think about it. It's something to consider. I can't think of a specific reason where the caching would be a problem. I'd definitely limit it to a sane value though if we did this.

**Comment by facelessuser** [comment]
I'll audit the places where we use lower and see what kind of data we store. If we are using this on element content (text) that could be quite large, at the very least we may want to avoid caching those instances. I can't recall the different ways we use it, but preventing the cache from ballooning to really large sizes is important as well. I may only be using it on element names and attributes though which may be fine.

**Comment by facelessuser** [comment]
I don't see anything that is potentially problematic here for being cached. It all looks like mainly lowering element tags, attribute, names, a few attribute values, custom selector names, etc.

File | Line | Matches | Extensions | Context
-- | -- | -- | -- | --
css_match.py | 157 | 1 | py | return ((el.name if self.is_xml_tree(el) else util.lower(el.name)) == 'iframe') and self.is_html_tag(el)
css_match.py | 303 | 1 | py | if util.lower(k) == name:
css_match.py | 497 | 1 | py | return util.lower(name) if name is not None and not self.is_xml else name
css_match.py | 503 | 1 | py | return util.lower(prefix) if prefix is not None and not self.is_xml else prefix
css_match.py | 514 | 1 | py | direction = DIR_MAP.get(util.lower(self.get_attribute_by_name(node, 'dir', '')), None)
css_match.py | 614 | 2 | py | if (self.is_xml and attr == k) or (not self.is_xml and util.lower(attr) == util.lower(k)):
css_match.py | 627 | 2 | py | if (util.lower(attr) != util.lower(name)) if not self.is_xml else (attr != name):
css_match.py | 634 | 2 | py | if util.lower(attr) != util.lower(k):
css_match.py | 684 | 1 | py | name = (util.lower(tag.name) if not self.is_xml and tag.name is not None else tag.name)
css_match.py | 1000 | 1 | py | if v and util.lower(v) == 'submit':
css_match.py | 1051 | 2 | py | if util.lower(k) == 'type' and util.lower(v) == 'radio':
css_match.py | 1053 | 1 | py | elif util.lower(k) == 'name' and v == name:
css_match.py | 1055 | 1 | py | elif util.lower(k) == 'checked':
css_match.py | 1085 | 1 | py | ((not has_ns or has_html_ns) and (util.lower(k) if not self.is_xml else k) == 'lang') or
css_match.py | 1088 | 1 | py | (util.lower(attr) if not self.is_xml and attr is not None else attr) == 'lang'
css_match.py | 1129 | 2 | py | if util.lower(k) == 'http-equiv' and util.lower(v) == 'content-language':
css_match.py | 1131 | 1 | py | if util.lower(k) == 'content':
css_match.py | 1165 | 1 | py | direction = DIR_MAP.get(util.lower(self.get_attribute_by_name(el, 'dir', '')), None)
css_match.py | 1179 | 1 | py | itype = util.lower(self.get_attribute_by_name(el, 'type', '')) if is_input else ''
css_match.py | 1229 | 1 | py | itype = util.lower(self.get_attribute_by_name(el, 'type'))
css_parser.py | 227 | 1 | py | name = util.lower(key)
css_parser.py | 338 | 1 | py | name = util.lower(css_unescape(m.group('name')))
css_parser.py | 455 | 1 | py | case = util.lower(m.group('case')) if m.group('case') else None
css_parser.py | 463 | 1 | py | elif util.lower(attr) == 'type':
css_parser.py | 537 | 1 | py | pseudo = util.lower(css_unescape(m.group('name')))
css_parser.py | 561 | 1 | py | pseudo = util.lower(css_unescape(m.group('name')))
css_parser.py | 653 | 1 | py | mdict['name'] = util.lower(css_unescape(mdict['name']))
css_parser.py | 654 | 1 | py | content = util.lower(mdict.get('nth' + postfix))
css_parser.py | 842 | 1 | py | value = ct.SEL_DIR_LTR if util.lower(m.group('dir')) == 'ltr' else ct.SEL_DIR_RTL

**Comment by akx** [comment]
The cache is limited to 512 entries in my proposed PR #192. Might end up in some LRU evictions for some users, but it's certainly better than no cache, or infinite ballooning :)
