### ISSUE TITLE
Adjustments for Python 3.9 CI failures

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/soupsieve#201]
Ref #200

**Comment by sm-ghavami** [comment]
I have fixed this issue  in my new commit
The problem was with python3.9-dev version

**Comment by facelessuser** [comment]
I may break that change out only because we need to decide how and if we want to handle more custom pseudo classes.

**Comment by sm-ghavami** [comment]
I know. I just edited the workflow to fix this issue. You should decide about the future changes.
