### ISSUE TITLE
Wrong usage information for [attribute|=value] at https://facelessuser.github.io/soupsieve/selectors/basic/

### ISSUE THREAD

**Issue by Kovinda** [facelessuser/soupsieve#210]
Usage of the selector [attribute|=value] has been mixed up with the usage of selector [attribute!=value]

![Screenshot 2020-12-14 232425](https://user-images.githubusercontent.com/75525796/102116881-a1abb000-3e63-11eb-95e8-4418ad3d0c95.png)

**Comment by facelessuser** [comment]
Oh, just in the docs. I can see that happening... It was copying a ton of examples when I did that, I can imagine I copied the wrong thing for some.

**Comment by facelessuser** [comment]
Docs have been updated and re-deployed. Thanks for the report.
