### ISSUE TITLE
setup.py is mentioned in readme but there is no setup.py

### ISSUE THREAD

**Issue by vsajko** [facelessuser/soupsieve#244]
I see that setup.py is removed but it is still mentioned in https://github.com/facelessuser/soupsieve#installation
> If you want to manually install it from source, navigate to the root of the project and run
> 
> python setup.py build
> python setup.py install
> 
What would be a new way to build from source?

**Comment by facelessuser** [comment]
Ah, I forgot to update that 🤦🏻.

Ensure you have [`build`](https://pypi.org/project/build/) installed:

```console
$ python -m pip install build
```

Then just build the wheel

```console
$ python -m build -w
```

Then install

```console
$ python -m pip install dist/soupsieve-<ver>-<py-tag>.whl
```

**Comment by facelessuser** [comment]
I'll have to get a post fix out to at least update the docs
