### ISSUE TITLE
Missing BUILD.bazel  file in latest release

### ISSUE THREAD

**Issue by koolshwets17** [facelessuser/soupsieve#274]
pypi__soupsieve': BUILD file not found in directory 'pypi__soupsieve' of external repository

**Comment by facelessuser** [comment]
@koolshwets17 please provide more info. I have no idea what you are referring to. What I do know is that the latest version soupsieve is on PyPI and updates fine with pip:

```console
➜ python3 -m pip install -U soupsieve
Requirement already satisfied: soupsieve in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.5)
Collecting soupsieve
  Downloading soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
Downloading soupsieve-2.6-py3-none-any.whl (36 kB)
Installing collected packages: soupsieve
  Attempting uninstall: soupsieve
    Found existing installation: soupsieve 2.5
    Uninstalling soupsieve-2.5:
      Successfully uninstalled soupsieve-2.5
Successfully installed soupsieve-2.6
➜  python3
Python 3.11.8 (v3.11.8:db85d51d3e, Feb  6 2024, 18:02:37) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import soupsieve
>>>
```

**Comment by facelessuser** [comment]
It seems this has something to do with https://bazel.build/concepts/build-files? Either way, we do not use or support this and have no intentions currently to do so. If support was to be considered, we would need a detailed proposal of why this is valuable and why it should be added.
