### ISSUE TITLE
CSS selector breaks after 3 levels of parenting

### ISSUE THREAD

**Issue by ISBachvarov21** [facelessuser/soupsieve#276]
``` python
current_element = matched_element
parent_tags = []
    
# NOTE: Changing this to more than 2 levels up breaks the CSS selector.
# TODO: Submit issue to soupsieve
for _ in range(2):
    current_element = current_element.find_parent()
    if current_element:
        parent_tags.append(current_element.name)
    else:
        break
    
    print(f'Parent tags: {parent_tags}')
    css_selector = f'{" ".join(parent_tags)} {matched_element.name}'
    print(f'CSS selector: {css_selector}')
```
this piece of code breaks whenever I add more than 3 selector levels
you can find it inside backend/src/main.py on line 54 through 68 in the repo below
[repo for reproducing](https://github.com/ISBachvarov21/scrapeit)

you can run the code using docker
```bash
cd backend
docker compose up --build 
```
or using python and pypi
```bash
cd backend
pip install -r requirements.txt
python main.py
```

is this an intended feature as to not waste a lot of resources, or is it a bug?
currently using html5lib, tried on html.parser, but to no avail

**Comment by facelessuser** [comment]
I'm not exactly sure I understand your issue.

> this piece of code breaks whenever I add more than 3 selector levels

What does this mean? How does it break? Can you provide me with a minimal, reproducible example? 

I really don't want to debug your repo looking for a bug. I'm happy to fix issues that are problematic (if they truly are), but I need clear, precise examples. This should be able to be broken down into a simple case. Please provide a simple example showing what you perceive to be faulty behavior.

**Comment by ISBachvarov21** [comment]
Upon writing an example to reproduce this issue, I have found out that the selectors I have been using aren't in the correct order. Sorry for wasting your time.

**Comment by facelessuser** [comment]
@ISBachvarov21 No worries, that is why I require minimal examples, sometimes the complexity of everything else can obscure what the real issue is.
