### ISSUE TITLE
css_parser regex broken for python < 2.7.5

### ISSUE THREAD

**Issue by mbhargav294** [facelessuser/soupsieve#63]
Python: 2.7.3
OS: RHEL
Dependency graph: [MechanicalSoup](https://github.com/MechanicalSoup/MechanicalSoup) → beauthifulsoup4 → soupsieve

With beautifulsoup4 4.7.0 soupsieve is installed as a dependency. Seems like python 2.7.3 had some issues in parsing one of the regular expressions in css_parser.py (RE_LANG to be specific). Do you have any plans on supporting python 2.7.4 or lower?

Here is the full stack trace for this issue:
```
File "~/virtualenvs/<venv>/lib/python2.7/site-packages/mechanicalsoup/__init__.py", line 2, in <module>
  from .browser import Browser
File "~/virtualenvs/<venv>/lib/python2.7/site-packages/mechanicalsoup/browser.py", line 2, in <module>
  import bs4
File "~/virtualenvs/<venv>/lib/python2.7/site-packages/bs4/__init__.py", line 34, in <module>
  from .builder import builder_registry, ParserRejectedMarkup
File "~/virtualenvs/<venv>/lib/python2.7/site-packages/bs4/builder/__init__.py", line 7, in <module>
  from bs4.element import (
File "~/virtualenvs/<venv>/lib/python2.7/site-packages/bs4/element.py", line 12, in <module>
  import soupsieve
File "~/virtualenvs/<venv>/lib/python2.7/site-packages/soupsieve/__init__.py", line 30, in <module>
  from . import css_parser as cp
File "~/virtualenvs/<venv>/lib/python2.7/site-packages/soupsieve/css_parser.py", line 144, in <module>
  RE_LANG = re.compile(r'(?:(?P<value>{value})|(?P<split>{ws}*,{ws}*))'.format(ws=WSC, value=VALUE), re.X)
File "~/virtualenvs/<venv>/lib/python2.7/re.py", line 190, in compile
  return _compile(pattern, flags)
File "~/virtualenvs/<venv>/lib/python2.7/re.py", line 242, in _compile
  raise error, v # invalid expression
sre_constants.error: nothing to repeat
```

**Comment by facelessuser** [comment]
Hmm, that is a pretty old version of Python 2.7.  I don't explicitly test versions that old.  I probably have no intentions of explicitly supporting anything below 2.7.

If the fix is easy enough, I don't mind adding it for < 2.7.5. I'd have to first identify what the issue is first.  It looks like we would be providing a workaround for a bug in the old regex version in regards to `*` patterns I imagine, but I'm not sure yet.

**Comment by facelessuser** [comment]
I'll have to see if I can even get access to a python version that old...

**Comment by facelessuser** [comment]
Worse case scenario, I think I can disable selectors that I cannot make work for Python < 2.7.5.  I should be able to setup a portable Python 2.7.4.1 environment on my system to at least analyze the issue.  If I can confirm, and more importantly resolve, then I'll add a fix.  If I can't resolve the issue, I may just disable that selector for Python < 2.7.5.

**Comment by facelessuser** [comment]
FYI, this is not related to < 2.7.5, but is instead seems to be < 2.7.4.  The issue is actually this sub-pattern:

```python
VALUE = r'''(?:"(?:\\.|[^\\"]*)*?"|'(?:\\.|[^\\']*)*?'|{ident}+)'''.format(ident=IDENTIFIER)
```

It should be as follows to work on older Python 2.7:

```python
VALUE = r'''(?:"(?:\\.|[^\\"]+)*?"|'(?:\\.|[^\\']+)*?'|{ident}+)'''.format(ident=IDENTIFIER)
```

Subtle.  It shouldn't normally break a regular expression engine, but using `+` in this case does make more sense.
