### ISSUE TITLE
:nth-of-type and :nth-child works only up to the 9th element

### ISSUE THREAD

**Issue by naslundx** [facelessuser/soupsieve#78]
Not sure where to file this bug as I'm using soupsieve via BeautifulSoup4, but here goes:

Using BeautifulSoup4 4.7.1, with SoupSieve 1.6.2, under Python 3.6.

```py
import bs4

source = """<html><body>
<div>1</div>
<div>2</div>
<div>3</div>
<div>4</div>
<div>5</div>
<div>6</div>
<div>7</div>
<div>8</div>
<div>9</div>
<div>10</div>
<div>11</div>
<div>12</div>
<div>12</div>
<div>13</div>
<div>14</div>
<div>15</div>
<div>16</div>
</body></html>"""
soup = bs4.BeautifulSoup(source, 'lxml')  # same result with html5lib

print(soup.select("div:nth-of-type(9)"))  # Expect 9, is 9
print(soup.select("div:nth-child(9)"))  # Expect 9, is 9
print(soup.select("div:nth-of-type(10)"))  # Expect 10, is 15
print(soup.select("div:nth-child(10)"))  # Expect 10, is 15
print(soup.select("div:nth-of-type(11)"))  # Expect 11, is 16
print(soup.select("div:nth-child(11)"))  # Expect 11, is 16
print(soup.select("div:nth-of-type(12)"))  # Expect 12, finds nothing
print(soup.select("div:nth-child(12)"))  # Expect 12, finds nothing
```

It seems to work well with single-digit index, but either returns empty or the wrong element for 10 and upwards.

(Also filed this on BS4 LaunchPad.)

**Comment by naslundx** [comment]
Note: Selecting `div:nth-of-type(n+9)` actually gives me the 9th div and onwards, so that seems to work fine. `div:nth-of-type(n+10)` gives me element 15 and 16.

**Comment by facelessuser** [comment]
Thanks for the report! I'll confirm the bug, and if reproducable, I'll get a fix out real soon.  Can't believe I missed such a simple case as `:nth-child(10)`  :man_facepalming: .

**Comment by facelessuser** [comment]
Oh, man...I was converting the string representation of the number to base 16 instead of 10, so as soon as you give an input greater than 9, you start getting things like 16 because `10` is `16` in base 16.

**Comment by facelessuser** [comment]
Thanks for pointing this out, I was getting close to pushing a new release that had a couple of minor bug fixes and a few new selectors, but this was a big issue.

I must have gotten confused as I have to convert hex values in base 16 for character escapes, but here I should have been converting decimal numbers with base 10.  And since I hadn't tested the input boundary past 9, I didn't notice the mistake.

**Comment by naslundx** [comment]
I did start suspecting hex values. :) Many thanks for a quick fix!

**Comment by facelessuser** [comment]
Yeah, I got stop counting with my 16 fingers when I code 🙂 .
